<?php
require_once('../connection.php');
require_once('config/auth.php');

$page_title = 'Coordinator Dashboard Hub';

// Fetch Counts for Dashboard
// 1. Direct Admissions
$direct_count_res = mysqli_query($con, "SELECT COUNT(*) as total FROM registration WHERE coordinator_approval_status = 1 AND reg_status = 0 AND bid = $coordinator_bid");
$direct_count = mysqli_fetch_assoc($direct_count_res)['total'];

// 2. Supervisor Registrations (reg_status = 2)
$reg_count_res = mysqli_query($con, "SELECT COUNT(*) as total FROM registration WHERE reg_status = 2 AND coordinator_approval_status = 0 AND bid = $coordinator_bid");
$reg_count = mysqli_fetch_assoc($reg_count_res)['total'];

include('includes/header.php');
?>
<div class="wrapper d-flex">
    <?php include('includes/sidebar.php'); ?>

    <div id="content" class="flex-grow-1">
        
        <!-- Welcome Header (Minimal) -->
        <div class="d-flex flex-column flex-md-row justify-content-between align-items-md-center mb-5 gap-3">
            <div>
                <h1 class="fw-bold mb-1 h3">Dashboard Hub</h1>
                <p class="text-muted mb-0 small"><i class="fas fa-building me-1 opacity-50"></i><?php echo htmlspecialchars($coordinator_bname); ?> Branch</p>
            </div>
            <div class="d-flex align-items-center gap-2">
                <div class="p-2 px-3 bg-white border rounded-pill shadow-sm small fw-medium">
                    <i class="far fa-calendar-alt text-muted me-2"></i><?php echo date('D, d M Y'); ?>
                </div>
            </div>
        </div>

        <!-- Quick Summary Cards (Soft UI) -->
        <div class="row g-4 mb-5">
            <div class="col-md-6">
                <a href="direct_approvals.php" class="hub-option">
                    <div class="minimal-card hub-card blue h-100">
                        <div class="d-flex justify-content-between align-items-center mb-3">
                            <div class="icon-box-minimal bg-primary bg-opacity-10 text-primary">
                                <i class="fas fa-headset fa-xl"></i>
                            </div>
                            <span class="badge-minimal badge-blue"><?php echo $direct_count; ?> Pending</span>
                        </div>
                        <h4 class="fw-bold mb-1">Direct Admissions</h4>
                        <p class="text-muted small mb-0">Confirm students flagged for immediate commission payout by callers.</p>
                    </div>
                </a>
            </div>
            <div class="col-md-6">
                <a href="reg_credentials.php" class="hub-option">
                    <div class="minimal-card hub-card purple h-100">
                        <div class="d-flex justify-content-between align-items-center mb-3">
                            <div class="icon-box-minimal bg-purple bg-opacity-10 text-purple" style="color: #8b5cf6 !important; background: rgba(139, 92, 246, 0.1) !important;">
                                <i class="fas fa-user-shield fa-xl"></i>
                            </div>
                            <span class="badge-minimal badge-purple"><?php echo $reg_count; ?> Awaiting</span>
                        </div>
                        <h4 class="fw-bold mb-1">Registration Approvals</h4>
                        <p class="text-muted small mb-0">Approve IDs and Passwords generated by the branch supervisor for online registration.</p>
                    </div>
                </a>
            </div>
        </div>

        <!-- Secondary Section: Logs & Activity -->
        <div class="row">
            <div class="col-12">
                <div class="minimal-card p-4">
                    <div class="d-flex justify-content-between align-items-center mb-4">
                        <h5 class="fw-bold mb-0">Operational Shortcuts</h5>
                    </div>
                    
                    <div class="list-group list-group-flush border-0">
                        <a href="past-approvals.php" class="list-group-item list-group-item-action border-0 px-0 d-flex align-items-center justify-content-between py-3">
                            <div class="d-flex align-items-center">
                                <div class="bg-slate-100 p-2 rounded-3 me-3" style="background: #f1f5f9;">
                                    <i class="fas fa-history text-slate-700"></i>
                                </div>
                                <div>
                                    <p class="mb-0 fw-semibold text-dark">Audit Trail & History</p>
                                    <span class="text-muted small">View all previously approved and rejected registrations.</span>
                                </div>
                            </div>
                            <i class="fas fa-chevron-right text-muted x-small"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php include('includes/footer.php'); ?>
